language: julia
julia:
  - 1.3
  - 1.4
  - nightly

matrix:
  allow_failures:
  - julia: nightly

before-install:

  - sudo apt-get install python3-scipy

script:
  - julia --color=yes -e "using Pkg; Pkg.activate(); Pkg.instantiate(); Pkg.test(coverage=true)"

after-success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'